name: local_file
description: "A new Flutter project."
homepage: https://github.com/websofter/flutter-pdf-rest-demo
repository: https://github.com/websofter/flutter-pdf-rest-demo
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.0.0+1
  syncfusion_flutter_pdfviewer:
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
